### ISSUE TITLE
Panic: concurrent write to websocket connection

### ISSUE THREAD

**Issue by mche** [marcos-gonalons/tradingview-scraper#5]
Hi,

### Here my simple app

```
package main

import (
	"log"

	socket "github.com/marcos-gonalons/tradingview-scraper/v2"
)

func main() {
    tradingviewsocket, err := socket.Connect(
        func(symbol string, data *socket.QuoteData) {
            log.Printf("%#v", symbol)
            log.Printf("%#v", data)
        },
        func(err error, context string) {
            log.Printf("%#v", "error -> "+err.Error())
            log.Printf("%#v", "context -> "+context)
        },
    )
    if err != nil {
        panic("Error while initializing the trading view socket -> " + err.Error())
    }
	log.Printf(`Open websocket: %+v`, tradingviewsocket)
	ch := make(chan int)
	<- ch
}
```

### Here fail:

```
.\trading-view.exe
2022/11/11 14:42:08 socket: &{OnReceiveMarketDataCallback:0x1197a00 OnErrorCallback:0x1197ae0 conn:0xc0001de160 isClosed:false sessionID:qs_zIEtTavgxWra}
panic: concurrent write to websocket connection

goroutine 12799 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc00018c120, 0x1, {0x0?, 0x0?, 0x0?})
        C:/Users/mche/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:610 +0x52b
github.com/gorilla/websocket.(*messageWriter).Close(0x0?)
        C:/Users/mche/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:724 +0x45
github.com/gorilla/websocket.(*Conn).beginMessage(0xc0001de160, 0xc000078960, 0x1)
        C:/Users/mche/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:473 +0x42
github.com/gorilla/websocket.(*Conn).NextWriter(0xc0001de160, 0x1)
        C:/Users/mche/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:513 +0x45
github.com/gorilla/websocket.(*Conn).WriteMessage(0x0?, 0x7e?, {0xc00006a000, 0xf, 0x200})
        C:/Users/mche/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:766 +0x152
github.com/marcos-gonalons/tradingview-scraper/v2.(*Socket).connectionLoop.func1(0x1, {0xc00006a000, 0xf, 0x200})
        C:/Users/mche/go/pkg/mod/github.com/marcos-gonalons/tradingview-scraper/v2@v2.1.1/socket.go:166 +0x112
created by github.com/marcos-gonalons/tradingview-scraper/v2.(*Socket).connectionLoop
        C:/Users/mche/go/pkg/mod/github.com/marcos-gonalons/tradingview-scraper/v2@v2.1.1/socket.go:160 +0x45
```

### I have go1.18.3

What is my mistake? Thank you.

**Comment by marcos-gonalons** [comment]
@mche  Concurrent writes only happen if you have more than 1 connection to the socket active, so my guess is that you already had an active connection before executing that code
